### ISSUE TITLE
MA10421 recognized as MA10660 and therefore not working anymore

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#14]
My old install worked - I switched to a Homebridge Raspbian Image for ease of use and stability and therefore updated homebridge-mobilealerts v1.1.4 (current latest).
My MA10200 and MA10100 still works well.

But my MA10421, which used to work well, now shows as "not supported". The accessory setting in the home app shows it is reconsidering as a MA10660, which is actually not supported.
The accessories work well in the Mobile Alerts app.
I tried putting "reset": true in the configuration file without success.

Have a great day!

![0A1FCDDE-1CDA-4BC7-87CF-200957B38D82](https://user-images.githubusercontent.com/6543748/85897042-ccdd0d00-b7f9-11ea-95a7-6046bb64d59b.jpeg)

**Comment by dehsgr** [comment]
Published a hotfix. Hope this helps.

**Comment by jerome71** [comment]
Thanks for the hotfix.
However, I now get an error message, Homebridge fails to launch, and gets into a loop trying to launch.
It launches OK if I remove the Mobile Alerts part of configuration.json.

The interesting line in the log seems to be: "[6/27/2020, 17:26:27] ReferenceError: cleanUmlaute is not defined
    at MobileAlerts.OnFinishLaunching (/usr/local/lib/node_modules/homebridge-mobilealerts/index.js:165:4)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)"

And here is the total log for a loop
[6/27/2020, 17:26:22] [HB Supervisor] Restarting Homebridge...
[6/27/2020, 17:26:22] [HB Supervisor] Starting Homebridge with extra flags: -I
[6/27/2020, 17:26:22] [HB Supervisor] Started Homebridge v1.1.1 with PID: 6537
[6/27/2020, 17:26:24] Loaded config.json with 0 accessories and 3 platforms.
[6/27/2020, 17:26:24] ---
[6/27/2020, 17:26:25] Loaded plugin: homebridge-config-ui-x@4.23.1
[6/27/2020, 17:26:25] Registering platform 'homebridge-config-ui-x.config'
[6/27/2020, 17:26:25] ---
[6/27/2020, 17:26:26] Loaded plugin: homebridge-harmony@1.3.11
[6/27/2020, 17:26:26] Registering platform 'homebridge-harmony.HarmonyHubWebSocket'
[6/27/2020, 17:26:26] ---
[6/27/2020, 17:26:26] Loaded plugin: homebridge-mobilealerts@1.1.5
homebridge API Version: 2.6
[6/27/2020, 17:26:26] Registering platform 'homebridge-mobilealerts.MobileAlerts'
[6/27/2020, 17:26:26] ---
[6/27/2020, 17:26:26] Loading 3 platforms...
[6/27/2020, 17:26:26] [Config] Initializing config platform...
[6/27/2020, 17:26:26] [Config] Running in Service Mode
[6/27/2020, 17:26:26] [Harmony Jérôme] Initializing HarmonyHubWebSocket platform...
[6/27/2020, 17:26:26] [Harmony Jérôme] HarmonyPlatform Init
[6/27/2020, 17:26:26] [MobileAlerts] Initializing MobileAlerts platform...
[6/27/2020, 17:26:26] [MobileAlerts] iPhone-ID was set to XXXXXXXX...
[6/27/2020, 17:26:26] [MobileAlerts] Polling Interval was set to 420s...
[6/27/2020, 17:26:26] [MobileAlerts] Fetching Data...
[6/27/2020, 17:26:26] [Harmony Jérôme] DidFinishLaunching
[6/27/2020, 17:26:26] [Harmony Jérôme] (Harmony Jérôme)INFO - Loading activities...
[6/27/2020, 17:26:26] [MobileAlerts] Merging Sensors...
[6/27/2020, 17:26:26] [MobileAlerts] Waiting for initial Sensor Data...
Setup Payload:
X-HM://0024TGFIU70LK
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXXXXXXXX │     
    └────────────┘     
                       
[6/27/2020, 17:26:26] Homebridge is running on port 51144.
[6/27/2020, 17:26:27] [MobileAlerts] Updating Accessory Data...
[6/27/2020, 17:26:27] [MobileAlerts] Merging Sensors...
[6/27/2020, 17:26:27] ReferenceError: cleanUmlaute is not defined
    at MobileAlerts.OnFinishLaunching (/usr/local/lib/node_modules/homebridge-mobilealerts/index.js:165:4)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/27/2020, 17:26:27] Got SIGTERM, shutting down Homebridge...
[6/27/2020, 17:26:27] [Harmony Jérôme] INFO - shutdown
[6/27/2020, 17:26:28] [Harmony Jérôme] (Harmony Jérôme)Error - Error retrieving info from hub : WebSocket closed with reason: Normal connection closure (1000).-(1)
[6/27/2020, 17:26:32] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/27/2020, 17:26:37] [HB Supervisor] Restarting Homebridge...

**Comment by dehsgr** [comment]
Sorry. There was another bug. Published another commit yet.

**Comment by jerome71** [comment]
It's working perfectly now.
Thanks!

**Comment by dehsgr** [comment]
You are welcome.

**Comment by jerome71** [comment]
Updated to Homebridge-MobileAlerts plugin V1.2.0.
The MA10421 now appears as "Default Model" and appears as "non managed" in the Home app again.
:-(

**Comment by dehsgr** [comment]
I‘m sorry and will fix this ASAP. Can you provide the first two letters of sensors serial please?

**Comment by dehsgr** [comment]
...I think it should be 11. Am I right? I published another fix and would like you to confirm it is working now.

**Comment by jerome71** [comment]
Yes the 2 first letters of the sensor's serial are 11.

**Comment by jerome71** [comment]
Updated to 1.2.1 (I had previously reverted to 1.1.6) and it seems to work OK :-).
