### ISSUE TITLE
MA10410

### ISSUE THREAD

**Issue by lexx0006** [dehsgr/homebridge-mobilealerts#17]
Hello,
Thank you for bringing Mobile Alerts to Homebridge. I use the Technoline MA10410 weatherstation. Is it possible to add support with your Plug-in?
Best regards
Alex

**Comment by dehsgr** [comment]
Should be supported as it is content of MA10006. Can you confirm this?

**Comment by lexx0006** [comment]
Yes, it works! :-)



Is it possible to hide sensors in Homebridge? (even though they are visible in Mobile Alert)



---
http://n4d.at.st
n4d@icloud.com


Am 12. Januar 2021 um 12:35 schrieb dehsgr <notifications@github.com>:






Should be supported as it is content of MA10006. Can you confirm this?

**Comment by dehsgr** [comment]
Nope. Hiding is not possible. But you might move sensor to another page at the end of your HomeBridge configuration and exclude it from favorites and status display.

**Comment by lexx0006** [comment]
OK, thank you for your help! :-)



---
http://n4d.at.st
n4d@icloud.com


Am 14. Januar 2021 um 12:19 schrieb dehsgr <notifications@github.com>:






Nope. Hiding is not possible. But you might move sensor to another page at the end of your HomeBridge configuration and exclude it from favorites and status display.

**Comment by lexx0006** [comment]
Sorry that I am back again…now I have another problem & I don´t know why!
Maybe you can help me:

[1/14/2021, 6:36:46 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 026c3364-fed3-450a-93d4-6cd33b3de312
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:310:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[1/14/2021, 6:36:46 PM] Got SIGTERM, shutting down Homebridge...
[1/14/2021, 6:36:46 PM] [N4D-Hub] INFO - shutdown

Do you have an idea?

**Comment by dehsgr** [comment]
Sorry. This issue is not related to this plugin. I would like you to ask directly at the homebridge repository.

**Comment by lexx0006** [comment]
As soon as I install your Mobile Alerts plugin with any ffmpeg camera plugin (there are many of them) I get this error … 
if I delete one of the two plugins (yours or that of the camera) homebridge works again! Very strange… ;-)

**Comment by dehsgr** [comment]
I think there might be a configuration issue with your bridge, if it runs when you only use one plugin. Maybe you could check your config.json syntax for errors. Homebridge is running each plugin with its dependencies from its own directory. So I would not imagine any inteferences here.
