### ISSUE TITLE
Homebridge fails to start 

### ISSUE THREAD

**Issue by Dave7NL** [dehsgr/homebridge-mobilealerts#28]
With the pluging configured Homebridge no longer starts : 

[4/17/2022, 8:26:06 AM] TypeError: Cannot read property 'language' of undefined
    at new MobileAlerts (/usr/lib/node_modules/homebridge-mobilealerts/index.js:51:34)
    at /usr/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)

As soon as i remove the configuration - it works.

**Comment by dehsgr** [comment]
@Dave7NL, I would like you to match your config according documentation. Since v2.0.0 there are a lot of changes!
