### ISSUE TITLE
Mobilealerts 1.0.5 crash after update

### ISSUE THREAD

**Issue by yanmeyer** [dehsgr/homebridge-mobilealerts#6]
I was running v 1.0.4 and it was working, even if I need to run again Homebridge once a day.
I have tried to update this morning to v 1.0.5.
But I can't now run Homebridge or Screen Homebridge without error:

[2018-9-20 08:25:17] [MobileAlerts] Initializing MobileAlerts platform...
/opt/node/lib/node_modules/homebridge-mobilealerts/index.js:58
  this.VerboseLogging = this.Config.log.verbose || false;
                                        ^

TypeError: Cannot read property 'verbose' of undefined
    at new MobileAlerts (/opt/node/lib/node_modules/homebridge-mobilealerts/index.js:58:41)
    at Server._loadPlatforms (/opt/node/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/opt/node/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/opt/node/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/opt/node/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Thank you for helping.

PS I'm using La Cross sensors : http://www.lacrossetechnology.fr/R-25-A1-0-objets-connectes.html
MA10001
MA10200
MA10350
MA10700

**Comment by dehsgr** [comment]
Sorry. My Mistake. As a workaround you might add the following to your config file (within MA-section):
`"log": { "verbose": false, "HTML": false }`

A bugfix release will pe published shortly.

**Comment by yanmeyer** [comment]
1) Now from version 1.0.5 to 1.0.9.  It appeared a problem (not sure if it was ok in 1.0.4) with MA10350 and H2O sensor and alerts which is alway in alarm even if it's no water. Perhaps a translation problem.

2) A nice feature for Europa would be the support of the accented characters like : é è à (My phone ID _removed for security reasons_)
![img_1239](https://user-images.githubusercontent.com/35530209/45939383-672f7180-bfd2-11e8-8520-d7fdcb46054d.PNG)

Have a nice day, Yannick

**Comment by dehsgr** [comment]
@yanmeyer I uploaded a fix for this. Before leaks didn't get displayed correctly. Now it indicates missing translations too, if a leak is detected. I added the correct translation so your sensor should say it's dry...

**Comment by yanmeyer** [comment]
Just Great, everything is working perfectly with version 1.0.10. I can't explain how you can do this so quickly ;-)

Envoyé de mon iPhone ...
